/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se_movies;

import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.*;//importacion de la Libreria JNI

/**
 *
 * @author gabri
 */
public class FRCONSULTA extends javax.swing.JFrame {

    /**
     * Creates new form FRCONSULTA
     */
FRESTADO ventana1 =new FRESTADO();//Datos de Que selecciono el usuario : pensativo , triste_enojado ,feliz
FRSENTIR ventana2 =new FRSENTIR();//Datos de Que selecciono el  : pensar, felicidad ,tristeza
FRCOMPANIA ventana3 =new FRCOMPANIA();//Datos de Que selecciono el usuario :familia,  solo ,novia_esposa
FREDAD ventana4 =new FREDAD();//Datos de Que selecciono el usuario : mayor, menor
FRACTOR ventana5 = new FRACTOR();//Datos de Que selecciono el usuario :leonardo_dicaprio ,scarlet_johanson ,wil_smith
Environment clips; //Llamamos a la libreria clips
    public FRCONSULTA() {
        clips = new Environment();
        clips.load("BD_MOVIES.CLP");//cargamos nuestra base del conocimiento
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //vamos a mostrar lo que el usuario señalo de las preguntas
        jLabel1.setText(ventana1.sentimiento);
        jLabel2.setText(ventana2.querer);
        jLabel3.setText(ventana3.quien);
        jLabel4.setText(ventana4.edad);
        jLabel5.setText(ventana5.actor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Segun sus preferencias:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/interface.png"))); // NOI18N
        jButton1.setText("Consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/commerce-and-shopping.png"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //al momento de darle click los datos que escojio el usuario va a consultar a nuestra base del conocimiento
        String sentimientoS, quererQ, quienQ,edadE, actorA,rsp; //declaramos varibles de tipo STRING
        sentimientoS = ventana1.sentimiento; 
        quererQ = ventana2.querer; 
        quienQ = ventana3.quien; 
        edadE = ventana4.edad;        
        actorA = ventana5.actor; 
// Consulta en CLips     
//       CLIPS> (assert
//      (recomendacion_pelicula
//	(sentimiento pensativo)
//	(querer felicidad)
//	(quien familia)
//	(edad menor)
//	(actor wil_smith)

//implemtacion de la consulta CLIPS en JAVA Mediante un String
        rsp = "(assert" + 
        "(recomendacion_pelicula" +
        "(sentimiento  "+ sentimientoS +")" +
        "(querer " + quererQ +")" +
        "(quien " + quienQ +")" +
        "(edad " + edadE +")" +        
        "(actor " + actorA +")))";
        
        clips.eval(rsp);// va a cargar nuestra consulta en <Fact>
        clips.run();// ejecuta nuestra consulta
        
        String evaluador = "(find-all-facts ((?m recomendacion)) TRUE)"; //Consulta de todos los <Facts>
        
        FactAddressValue fv = (FactAddressValue) ((MultifieldValue) clips.eval(evaluador)).get(0);
        
        try {
//            (deftemplate recomendacion
//		(slot mensaje))
            String msj = fv.getFactSlot("mensaje").toString();// Vamos a guardar nuestro mensaje en una variable String
            JOptionPane.showMessageDialog(null, msj);// Le mostamos la recomendacion Mediante un JOptionpane
            clips.reset();// Resetiamos el clips para poder hacer mas consultas
            
        } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex);
//            Logger.getLogger(JOptionPane.showMessageDialog.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // En caso que el Usuario Quiera hacer una consulta vamos a limpiar todos los datos que el selecciono
        // y rederigirle a la pantalla de la primera pregunta ¿En que estado de animo te encuentras?
       // Limpiamos los datos de la pantallas
        ventana2.setVisible(false);
        ventana3.setVisible(false);
        ventana4.setVisible(false);
        ventana5.setVisible(false);
        this.setVisible(false); // ocultamos la pantalla de la consulta
        ventana1.setVisible(true); // Mostramos la primera pantalla
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRCONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRCONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRCONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRCONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRCONSULTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
